### ISSUE TITLE
Nothing happen after run dispatcher

### ISSUE THREAD

**Issue by rickywu** [131/dispatcher#2]
I use VS compiled and have two files in my folder:
bash.exe
bash.exe.config:
```

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="PATH" value="C:\Windows\System32\bash.exe"/>
    <add key="ARGV0" value="-c"/>
    <add key="ARGV1" value="/usr/sbin/sshd -D"/>
    <add key="USE_SHOWWINDOW" value="true"/>
  </appSettings>
</configuration>
```
But after I run bash.exe there is no any process named bash.exe, nothing happened
Any compiled binary available?

**Comment by rickywu** [comment]
after search, I did these:
chmod +s /usr/sbin/sshd

edit /etc/sudoers and add:
%sudo ALL=(ALL) NOPASSWD: /usr/sbin/sshd -D

Then I can start ssh server without window

**Comment by 131** [comment]
You can find compiled binaries in on github releases page https://github.com/131/dispatcher/releases/tag/v1.0.0
All good ?

**Comment by rickywu** [comment]
One more problem is I must start dispatcher using command prompt
If I run it with startup or call it from bat file then still nothing happened nor error occurred, any suggestion?

**Comment by rickywu** [comment]
Finally, I use start "d:\Program Files\" bash.exe to run dispatcher in bat file in order to run ti when startup system.

**Comment by 131** [comment]
I think you should try using dispatch_64.exe (in the release page) to spawn bash.exe properly (from any directory)
