### ISSUE TITLE
How to start dispatcher as a Service or Task?

### ISSUE THREAD

**Issue by philipsd6** [131/dispatcher#3]
Any suggestions for running a dispatcher as a service at logon, or as a scheduled task at logon? 

I have a dispatcher correctly configured to run WSL SSH service, but when I add it to the Task Scheduler, it fails to launch (code 2147956401) and I haven't been able to get it working that way, even though I am local admin on this machine.

**Comment by philipsd6** [comment]
Never mind, I had a last second regression bug in my config... working now.

**Comment by 131** [comment]
I use the windows task scheduler, with nice feedback
