### ISSUE TITLE
Dispatcher became slow after reinstalling Windows 10

### ISSUE THREAD

**Issue by oxou** [131/dispatcher#6]
I've reinstalled my OS, and kept the folder that I always reference in the %PATH% intact as it was previously.

So now whenever I run any command routed through Dispatcher it takes a second for the command to fire up.

I've specifically crafted a workspace for myself where I use the busybox executable and then route the built-in commands through Dispatcher to avoid annoying Command Prompt messages and some issues with internal tools.

Busybox is not the only utility I use, so I can confirm that the busybox utility is not the issue here, I have GNU Nano cross-compiled to Windows, I have Git, NodeJS, Python, Ruby, etc... all of these commands now take 1 second to output anything.

All I did was reinstall my OS to the same 22H2 build as prior, installed all dependencies like DirectX, .NET Runtime, Frameworks, etc.

Currently I do not have a local copy of VS so that I can compile this myself and debug it, and getting that copy is gonna take a long time due to my connection being so slow.

**Comment by 131** [comment]
Thank for the PR. Merged.
