### ISSUE TITLE
Is it possible to have PIPES or prepended arguments?

### ISSUE THREAD

**Issue by oxou** [131/dispatcher#8]
I have a `diff` utility referenced through Dispatcher which actually points to `busybox`.

Now because that implementation does not provide color output, I decided to write a script in PHP that reads STDIN, adds in the colors and writes back to STDOUT.

![image](https://user-images.githubusercontent.com/102489121/227263187-af379cae-f2d4-45ed-bd08-47095a2c1c4f.png)

Would it be possible to have this PIPE defined via Dispatcher?

Where specifying `diff a.js b.js` would result in `busybox diff a.js b.js | php C:\env\bin\standalone-php\diff-colors-hack.php`

**Comment by 131** [comment]
hmmm.
What might be the config syntax proposal for that ?

**Comment by 131** [comment]
For now, I think this will send dispatcher in a very complex path.
I postpone this until a "revelation".
